### ISSUE TITLE
.obsidian.vimrc not working

### ISSUE THREAD

**Issue by kg-h** [esm7/obsidian-vimrc-support#71]
When I map without the vimrc (just type ```:imap jk <Esc>``` in Obsidian) it works, but none of the mappings work when I put them in the .obsidian.vimrc unless I enable vim mode display which is super buggy. Im on MacOS.

**Comment by esm7** [comment]
Can you open the Obsidian Developer Console (Cmd+Shift+I), restart Obsidian and paste the logs you see in the Console tab when you open the app and then some note?

**Comment by kg-h** [comment]
Uncaught (in promise) Error: ENOENT: no such file or directory, scandir '/Users/howard/OneDrive/Obsidian Vault/css-snippets'
main.ts:94 Error loading vimrc file .obsidian.vimrc from the vault root Error: ENOENT: no such file or directory, open '/Users/howard/OneDrive/Obsidian Vault/.obsidian.vimrc'

It says there is no such file .obsidian.vimrc

**Comment by esm7** [comment]
Can you copy the complete console from the very beginning? I want to see the initialization log of the plugin.
Which version of the plugin are you using, is it the latest 0.5.0? And which version of Obsidian?

**Comment by kg-h** [comment]
I'm using version 0.5.0 of the plugin and v0.13.14 of Obsidian

```
Obsidian Developer Console
main.ts:85 Vimrc plugin: using CodeMirror 6 mode
main.ts:94 Error loading vimrc file .obsidian.vimrc from the vault root TypeError: Cannot read property 'cm' of undefined
    at VimrcPlugin.getCodeMirror (eval at <anonymous> (app.js:1), <anonymous>:530:95)
    at VimrcPlugin.readVimInit (eval at <anonymous> (app.js:1), <anonymous>:538:33)
    at eval (eval at <anonymous> (app.js:1), <anonymous>:452:70)
```

**Comment by esm7** [comment]
I couldn't recreate this to verify, but I think I know what went wrong. Can you check if 0.5.1 that I just released fixes the issue?

**Comment by kg-h** [comment]
just checked version 0.5.1 still doesn't work, though there are no longer any errors in the console.

**Comment by yarinm** [comment]
I'm having the same issue as well

**Comment by esm7** [comment]
Which editor are you guys using, the legacy or the new one?

**Comment by esm7** [comment]
I'm trying to find more hints because I can't recreate this in any combination that I try, nor find a theoretical cause. @kg-h you originally wrote "unless I enable vim mode display". Does it mean that when you turn on "Vim mode display" in the plugin settings, your Vimrc works?!
Also, if one of you guys can attach a screenshot of the plugin settings pane and your Vimrc file (plus its full name) it can help.

**Comment by kg-h** [comment]
@esm7 It works if I enable vim mode display, though vim mode display does not work properly as the insert mode display is still enabled when i escape to normal mode.

![image](https://user-images.githubusercontent.com/89951530/147348422-e04c8105-0bbe-49a5-8bd3-b052baf8892c.png)

![image](https://user-images.githubusercontent.com/89951530/147348493-126a2571-3b24-4fd2-819b-f0a82307ba90.png)

**Comment by esm7** [comment]
In the same Developer Console as previously, can you type the following *when a note is open* and send me the results?
1. `app.workspace.activeLeaf.view.sourceMode.cmEditor`
2. `app.workspace.activeLeaf.view.sourceMode.cmEditor.cm`
3. `app.workspace.activeLeaf.view.sourceMode.cmEditor.cm.cm`
For the last two, if you get something other than `undefined`, a screenshot or copy of the expanded output could be helpful.

**Comment by kg-h** [comment]
```
Obsidian Developer Console
main.ts:85 Vimrc plugin: using CodeMirror 6 mode
main.ts:30 loading markdown-table-editor plugin
app.workspace.activeLeaf.view.sourceMode.cmEditor
CodeMirror {options: {…}, doc: Doc, display: Display, state: {…}, curOp: null, …}curOp: nulldisplay: Display {input: TextareaInput, scrollbarFiller: div.CodeMirror-scrollbar-filler, gutterFiller: div.CodeMirror-gutter-filler, lineDiv: div.CodeMirror-code, selectionDiv: div, …}doc: Doc {children: Array(10), size: 250, height: 5022, parent: null, first: 0, …}options: {mode: "templater", theme: "obsidian", lineWrapping: true, styleActiveLine: true, configureMouse: ƒ, …}state: {keyMaps: Array(1), overlays: Array(1), modeGen: 4, overwrite: false, delayingBlurEvent: false, …}_handlers: {beforeSelectionChange: Array(1), gutterClick: Array(1), changes: Array(2), viewportChange: Array(1), fold: Array(1), …}__proto__: Object
app.workspace.activeLeaf.view.sourceMode.cmEditor.cm
undefined
app.workspace.activeLeaf.view.sourceMode.cmEditor.cm.cm
VM143:1 Uncaught TypeError: Cannot read property 'cm' of undefined
    at <anonymous>:1:54
(anonymous) @ VM143:1
```

**Comment by esm7** [comment]
It seems like the plugin detects that you are using the new CM6 editor, but the actual editor object is the legacy one.
1. Do you have "Use legacy editor" turned on in your Editor settings?
2. Do you mind to also check the value of `this.app.vault.config.legacyEditor` in the Developer Console?

**Comment by kg-h** [comment]
Yea I have use legacy editor enabled 
![image](https://user-images.githubusercontent.com/89951530/147354981-31b2ccc3-2be6-4f58-a395-0489be365d6a.png)

app.vault.config.legacyEditor
undefined

**Comment by kg-h** [comment]
I just turned off legacy editor and now it works.

**Comment by esm7** [comment]
I'm shooting in the dark and guessing that if you turn legacy editor back on, it will now work too. Is that right?
The code that detects the legacy editor seems to be imperfect, I'll look for another way to do it.

**Comment by kg-h** [comment]
yea it behaves the same, works though vim display mode seems to be enabled with the blinking cursor.

**Comment by serpro69** [comment]
Had the same issue. Legacy Editor was enabled in settings, but that didn't take any effect with this plugin. After turning legacy editor off and on again - things started working fine. 
I think the reason for that is that when you get a pop-up asking if you want to keep legacy editor or not (with one of last obsidian updates), selecting the legacy editor option doesn't modify the `.obsidian/app.json` file properly (the `legacyEditor` option isn't added). But after I've disabled and re-enabled the option manually, I can see the app.json was modified with new config option being added:
```diff
-  "autoPairBrackets": false
+  "autoPairBrackets": false,
+  "legacyEditor": true
```

**Comment by esm7** [comment]
Indeed, you diagnosed the root cause correctly. I asked for a solution in the Discord dev channel and got a few suggestions, didn't have time to implement yet, hopefully next week.
